// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateBackup() {
  return window['go']['gui']['App']['CreateBackup']();
}

export function DeleteBackup(arg1) {
  return window['go']['gui']['App']['DeleteBackup'](arg1);
}

export function GetBackupPreview() {
  return window['go']['gui']['App']['GetBackupPreview']();
}

export function GetCleanerStatus() {
  return window['go']['gui']['App']['GetCleanerStatus']();
}

export function GetWiperStatus() {
  return window['go']['gui']['App']['GetWiperStatus']();
}

export function Greet(arg1) {
  return window['go']['gui']['App']['Greet'](arg1);
}

export function ListBackups() {
  return window['go']['gui']['App']['ListBackups']();
}

export function RestoreBackup(arg1) {
  return window['go']['gui']['App']['RestoreBackup'](arg1);
}

export function RunCleaner() {
  return window['go']['gui']['App']['RunCleaner']();
}

export function RunWiper(arg1) {
  return window['go']['gui']['App']['RunWiper'](arg1);
}
