// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gui} from '../models';

export function CreateBackup():Promise<gui.BackupInfo>;

export function DeleteBackup(arg1:string):Promise<void>;

export function GetBackupPreview():Promise<gui.BackupPreview>;

export function GetCleanerStatus():Promise<Array<gui.CleanerInfo>>;

export function GetWiperStatus():Promise<gui.WiperInfo>;

export function Greet(arg1:string):Promise<string>;

export function ListBackups():Promise<Array<gui.BackupInfo>>;

export function RestoreBackup(arg1:string):Promise<void>;

export function RunCleaner():Promise<void>;

export function RunWiper(arg1:number):Promise<void>;
